# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('flag', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='riplInd.acc_cat')),
            ],
        ),
        migrations.CreateModel(
            name='callme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/thu', verbose_name='img')),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('occupation', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=45)),
                ('con_pref', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('India', 'IN')], default='India', max_length=60)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='mat_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/upholstery', verbose_name='img')),
                ('flag', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.color')),
            ],
        ),
        migrations.CreateModel(
            name='pro_uph_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.material')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/', verbose_name='img')),
                ('added_on', models.CharField(default=datetime.datetime.now, max_length=200)),
                ('flag', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='riplInd.category')),
            ],
        ),
        migrations.CreateModel(
            name='servicing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('serial', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=45)),
                ('con_pref', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=450)),
                ('description', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='sub_upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('testing', models.ManyToManyField(to='riplInd.product')),
            ],
        ),
        migrations.CreateModel(
            name='upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=5)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pro_uph_options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.product'),
        ),
        migrations.AddField(
            model_name='material',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riplInd.sub_upholstery'),
        ),
        migrations.AddField(
            model_name='material',
            name='upholstery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.upholstery'),
        ),
    ]
