# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-07 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/acc_images', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='callme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=450, null=True)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='thu', verbose_name='img')),
                ('fimage', models.ImageField(upload_to='prothumb', verbose_name='Featured Image')),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_index_thumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category/index/thumbs', verbose_name='img')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riplInd.category')),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('occupation', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=450)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/dim_images', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='faqcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/feat_images', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/fun_images', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='gfaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=45)),
                ('answer', models.CharField(max_length=450)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riplInd.faqcategory')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upholstery', verbose_name='img')),
                ('flag', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.color')),
            ],
        ),
        migrations.CreateModel(
            name='mblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='mblog')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 7, 23, 8, 41, 557000))),
                ('author', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pro_uph_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riplInd.material')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='prothumb', verbose_name='Thumbnail')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='cover image')),
                ('added_on', models.CharField(default=datetime.datetime.now, max_length=200)),
                ('flag', models.BooleanField(default=True)),
                ('accessory', models.ManyToManyField(to='riplInd.accessory')),
                ('category', models.ManyToManyField(to='riplInd.category')),
                ('dimension', models.ManyToManyField(to='riplInd.dimension')),
                ('faq', models.ManyToManyField(to='riplInd.faq')),
                ('features', models.ManyToManyField(to='riplInd.feature')),
                ('function', models.ManyToManyField(to='riplInd.function')),
                ('material', models.ManyToManyField(to='riplInd.material')),
            ],
        ),
        migrations.CreateModel(
            name='servicing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('serial', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_title', models.CharField(max_length=45)),
                ('s_image', models.ImageField(upload_to='spare', verbose_name='img')),
                ('spare_desc', models.CharField(max_length=1000)),
                ('vendor_title', models.CharField(max_length=45)),
                ('v_image', models.ImageField(upload_to='spare/vendor', verbose_name='img')),
                ('vendor_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riplInd.countries')),
            ],
        ),
        migrations.CreateModel(
            name='sub_upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=5)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pro_uph_options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riplInd.product'),
        ),
        migrations.AddField(
            model_name='material',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riplInd.sub_upholstery'),
        ),
        migrations.AddField(
            model_name='material',
            name='upholstery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.upholstery'),
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riplInd.states'),
        ),
    ]
