# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/dim_images', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='prothumb/fun_images', verbose_name='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='desc',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default=1, upload_to='prothumb/acc_images', verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='fimage',
            field=models.ImageField(default=1, upload_to='prothumb', verbose_name='Featured Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='thu', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(upload_to='prothumb/feat_images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='prothumb', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='product',
            name='fun_images',
            field=models.ManyToManyField(to='riplInd.function'),
        ),
    ]
