# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0002_auto_20161224_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fun_images',
            new_name='function',
        ),
        migrations.AddField(
            model_name='product',
            name='accessory',
            field=models.ManyToManyField(to='riplInd.accessory'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.ManyToManyField(to='riplInd.dimension'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='riplInd.feature'),
        ),
    ]
