# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0003_auto_20161224_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.ManyToManyField(to='riplInd.faq'),
        ),
    ]
