# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0004_auto_20161224_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(to='riplInd.material'),
        ),
    ]
