# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0007_spares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(upload_to='upholstery', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='s_image',
            field=models.ImageField(upload_to='spare', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='v_image',
            field=models.ImageField(upload_to='spare/vendor', verbose_name='img'),
        ),
    ]
