# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0008_auto_20161226_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spares',
            old_name='s_title',
            new_name='spare_title',
        ),
        migrations.RenameField(
            model_name='spares',
            old_name='v_title',
            new_name='vendor_title',
        ),
    ]
