# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0009_auto_20161226_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='spare_desc',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spares',
            name='vendor_desc',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
