# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0010_auto_20161226_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='spare_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='spares',
            name='vendor_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
