# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0011_auto_20161226_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_index_thumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category/index/thumbs', verbose_name='img')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riplInd.category')),
            ],
        ),
    ]
