# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0012_category_index_thumbs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acc_cat',
        ),
        migrations.DeleteModel(
            name='mat_cat',
        ),
    ]
