# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0013_auto_20161227_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testing',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
