# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0014_auto_20161227_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='callme',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
