# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0015_callme_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='callme',
            name='remarks',
            field=models.CharField(default='No data added', max_length=450),
            preserve_default=False,
        ),
    ]
