# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0019_callme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callme',
            name='user',
        ),
    ]
