# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0021_callme_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='gfaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=45)),
                ('answer', models.CharField(max_length=450)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.category')),
            ],
        ),
    ]
