# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0022_faqcategory_gfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfaq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riplInd.faqcategory'),
        ),
    ]
