# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0023_auto_20161229_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callme',
            name='remarks',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='callme',
            name='user',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
