# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0024_auto_20161230_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='mblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='mblog')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 1, 7, 16, 54, 23, 230000))),
                ('author', models.CharField(max_length=45)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
    ]
