# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0026_auto_20170113_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='country',
            new_name='countries',
        ),
        migrations.RenameModel(
            old_name='state',
            new_name='states',
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 13, 11, 47, 45, 519000)),
        ),
    ]
