# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0027_auto_20170113_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default=1, upload_to='cover', verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 14, 12, 5, 6, 45000)),
        ),
    ]
