# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0029_auto_20170114_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riplInd.countries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 14, 17, 2, 35, 14000)),
        ),
    ]
