# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0030_auto_20170114_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 14, 17, 8, 28, 141000)),
        ),
    ]
