# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0032_auto_20170114_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='con_pref',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 14, 56, 26, 186000)),
        ),
    ]
