# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0033_auto_20170207_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callme',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 12, 28, 48, 336000)),
        ),
    ]
