# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0034_auto_20170208_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 12, 59, 31, 380000)),
        ),
    ]
