# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0035_auto_20170208_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='con_pref',
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 13, 12, 22, 178000)),
        ),
    ]
