# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0036_auto_20170208_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicing',
            old_name='city',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='servicing',
            name='con_pref',
        ),
        migrations.RemoveField(
            model_name='servicing',
            name='description',
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 13, 27, 49, 87000)),
        ),
    ]
