# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0037_auto_20170208_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicing',
            name='reason',
        ),
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 13, 33, 49, 663000)),
        ),
    ]
