# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riplInd', '0038_auto_20170208_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mblog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 13, 34, 50, 961000)),
        ),
        migrations.AlterField(
            model_name='servicing',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
